<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Add theme supports
 * - Block Styles
 * - Responsive Embed
 * - Editor Styles
 * - Disable Layout Styles
 */
add_action( 'after_setup_theme', function() {
    add_theme_support( 'wp-block-styles' );
    add_theme_support( 'responsive-embeds' );
    add_theme_support( 'editor-styles' );
    add_theme_support( 'disable-layout-styles' );
});

/**
 * Blocks
 * - secondary logo
 */
add_action('init', function() {
    register_block_type( __DIR__ . '/build/secondary-logo' );
});

/**
 * Enqueue Style for Block
 */
add_action( 'enqueue_block_assets', function() {
    // Automatically load dependencies generated by wp-scripts (like wp-blocks, wp-element)
    $asset_file = include get_template_directory() . '/build/index.asset.php';

    wp_enqueue_style( 
        'block-styles', 
        get_stylesheet_directory_uri() . '/build/index.css', 
        array(), 
        $asset_file['version'],
    );

});

/**
 * Register Site-meta for Secondary Logo
 */
add_action( 'init', function() {
    register_setting(
        'general',
        'my_custom_company_field',
        array(
            'show_in_rest' => true, // Crucial for Gutenberg/Site Editor access
            'type'         => 'string',
            'sanitize_callback' => 'sanitize_text_field',
        )
    );
});

